package recipe

import (
	"fmt"
	"strings"
	"testing"
)

// The regenerate suite drives the REAL pkg/waiver read path: every case below
// leaves ApplyOptions.ReadWaivers NIL, so the divergence is adjudicated by
// waiver.Adjudicate over the consumer's own file. A stubbed reader would bypass
// exactly the mechanism these tests exist to hold.

// regenerateRecipe declares the recipe-owned output plus the enforcement rule a
// divergence is adjudicated against. The kind is the ONLY thing that varies
// between the scaffolding and implementing halves of REQ-004, so it is a %s.
const regenerateRecipe = `
kind: %s
version: 1.0.0
enforcement:
  rules:
    - recipe.output.divergence
ops:
  - id: op-generate
    kind: create
    target: generated/recipe-owned.conf
    payload: body.txt
`

// regeneratedPayload is what the recipe reproduces on every apply. It is four
// lines long so a divergence can carry a waiver token on a line that is neither
// the first nor the second — see divergedWithTokenLine.
const regeneratedPayload = "# recipe-owned output\nalpha\nbravo\ncharlie\n"

// divergedWithTokenLine builds a consumer edit of the recipe-owned output that
// places tokenLine on LINE 4.
//
// THE LINE CONTRACT this encodes: waiver.Adjudicate associates a token with a
// finding through a {Line, Line-1} window only (pkg/waiver/adjudicate.go
// windowLines), so the synthesized divergence findings must span EVERY line of
// the diverged file — recipe-owned output includes formats with no comment slot
// at a fixed position. Line 4 is the falsifier: an applier that synthesized a
// single line-1 finding, or that only scanned the first window, would never see
// this token and would regenerate over it.
func divergedWithTokenLine(tokenLine string) string {
	return "# recipe-owned output\nalpha\nCONSUMER EDIT the recipe did not write\n" + tokenLine + "\ncharlie\n"
}

// adoptRecipeOwnedOutput applies recipeYAML once into a fresh project root,
// establishing the output as RECIPE-OWNED: the file on disk afterwards is one a
// previous apply produced, which is exactly what separates it from the
// user-owned file CLM-018 protects. It fails the test if the first apply did not
// materialize the declared target.
func adoptRecipeOwnedOutput(t *testing.T, recipeYAML string) (*ResolvedRecipe, string, Op) {
	t.Helper()

	recipeDir := t.TempDir()
	projectRoot := t.TempDir()

	resolved := resolvedFromManifest(t, recipeDir, recipeYAML)
	createOp := resolved.Manifest.Ops[0]
	writeUnder(t, recipeDir, createOp.Payload, regeneratedPayload)

	result, err := Apply(resolved, ApplyOptions{Mode: ModeDirect, ProjectRoot: projectRoot})
	if err != nil {
		t.Fatalf("first Apply: unexpected error: %v", err)
	}
	if got := snapshotTree(t, projectRoot)[createOp.Target]; got != regeneratedPayload {
		t.Fatalf("first apply produced %q at %q, want the recipe's declared payload %q", got, createOp.Target, regeneratedPayload)
	}
	if len(result.Written) != 1 || result.Written[0] != createOp.Target {
		t.Fatalf("first apply result.Written = %v, want exactly [%q]", result.Written, createOp.Target)
	}

	return resolved, projectRoot, createOp
}

// declaredEnforcementRule reads the rule a divergence is adjudicated against off
// the PARSED manifest, so no test hard-codes a rule id the applier could
// accidentally agree with.
func declaredEnforcementRule(t *testing.T, resolved *ResolvedRecipe) string {
	t.Helper()

	if resolved.Manifest.Enforcement == nil || len(resolved.Manifest.Enforcement.Rules) == 0 {
		t.Fatalf("test recipe declares no enforcement rules; a divergence has no rule id to be adjudicated against")
	}

	return resolved.Manifest.Enforcement.Rules[0]
}

// preservedFor returns the result's preserved entry for a declared target.
func preservedFor(result ApplyResult, target string) (PreservedDivergence, bool) {
	for _, preserved := range result.Preserved {
		if preserved.Path == target {
			return preserved, true
		}
	}
	return PreservedDivergence{}, false
}

// countWaiverTokens counts every @waiver occurrence across a whole project tree,
// so "the applier authored a token somewhere" cannot hide in a file the test did
// not think to probe.
func countWaiverTokens(tree map[string]string) int {
	total := 0
	for _, content := range tree {
		total += strings.Count(content, "@waiver:")
	}
	return total
}

// TestApply_Scaffolding_RegeneratesRecipeOwnedOutput proves recipe-owned output of
// a SCAFFOLDING recipe is regenerated by default (CLM-019). The consumer edit
// between the two applies carries NO waiver, so the second apply must reproduce
// the recipe's bytes: an applier that treated its own prior output as untouchable
// would let recipe-owned content drift silently, which is the failure this holds.
func TestApply_Scaffolding_RegeneratesRecipeOwnedOutput(t *testing.T) {
	assertRegeneratesRecipeOwnedOutput(t, KindScaffolding)
}

// TestApply_Implementing_RegeneratesRecipeOwnedOutput is the IMPLEMENTING half of
// the same model (CLM-020) — the two regenerating kinds must behave identically.
func TestApply_Implementing_RegeneratesRecipeOwnedOutput(t *testing.T) {
	assertRegeneratesRecipeOwnedOutput(t, KindImplementing)
}

// assertRegeneratesRecipeOwnedOutput holds the regenerate-by-default behavior for
// one kind: apply, edit the recipe-owned output, re-apply, and require the
// recipe's bytes back.
func assertRegeneratesRecipeOwnedOutput(t *testing.T, kind string) {
	t.Helper()

	resolved, projectRoot, createOp := adoptRecipeOwnedOutput(t, fmt.Sprintf(regenerateRecipe, kind))
	if resolved.Manifest.Kind != kind {
		t.Fatalf("parsed recipe kind = %q, want %q", resolved.Manifest.Kind, kind)
	}

	const consumerEdit = "# recipe-owned output\nalpha\nDRIFT the recipe must reproduce over\ncharlie\n"
	writeUnder(t, projectRoot, createOp.Target, consumerEdit)

	result, err := Apply(resolved, ApplyOptions{Mode: ModeDirect, ProjectRoot: projectRoot})
	if err != nil {
		t.Fatalf("re-apply: unexpected error: %v", err)
	}

	got := snapshotTree(t, projectRoot)[createOp.Target]
	if got != regeneratedPayload {
		t.Errorf("re-applied %s output = %q, want the recipe's declared payload %q — recipe-owned output regenerates by default", kind, got, regeneratedPayload)
	}
	if got == consumerEdit {
		t.Errorf("the undrifted consumer edit survived a re-apply of a %s recipe; only templating is one-shot", kind)
	}

	var regenerated bool
	for _, written := range result.Written {
		if written == createOp.Target {
			regenerated = true
		}
	}
	if !regenerated {
		t.Errorf("result.Written = %v, want the regenerated target %q", result.Written, createOp.Target)
	}
	if preserved, reported := preservedFor(result, createOp.Target); reported {
		t.Errorf("result reports %q as preserved (%+v); with no covering waiver the divergence is regenerated", createOp.Target, preserved)
	}
}

// TestApply_DivergedWithActiveWaiver_PreservedViaRealWaiverReadPath proves the
// accountable-divergence hinge runs through the REAL pkg/waiver read path
// (CLM-021): the consumer adds a genuine @waiver token to the recipe-owned file
// FIRST, and the re-apply preserves the on-disk bytes because waiver.Adjudicate
// put the divergence finding in Result.Suppressed.
//
// ReadWaivers is left nil in every sub-case, so the adjudication is the
// production one. The two falsifying twins are what separate adjudication from a
// substring match: an EXPIRED token must not preserve (the grammar's expiry is
// read and compared), and a token naming a DIFFERENT rule must not preserve (the
// rule key is real). The token sits on line 4 per the line contract, so a
// single-finding or first-window-only implementation fails the covering case.
func TestApply_DivergedWithActiveWaiver_PreservedViaRealWaiverReadPath(t *testing.T) {
	cases := []struct {
		name      string
		token     func(rule string) string
		preserved bool
	}{
		{
			name: "active_token_covers_the_divergence",
			token: func(rule string) string {
				return "# @waiver:" + rule + ":accepted-risk:2099-01-01 divergence accepted by the consumer"
			},
			preserved: true,
		},
		{
			name: "expired_token_does_not_cover",
			token: func(rule string) string {
				return "# @waiver:" + rule + ":accepted-risk:2000-01-01 the shield lifted when it expired"
			},
			preserved: false,
		},
		{
			name: "wrong_rule_id_does_not_cover",
			token: func(string) string {
				return "# @waiver:some.other.rule:accepted-risk:2099-01-01 waives a different rule entirely"
			},
			preserved: false,
		},
	}

	for _, testCase := range cases {
		t.Run(testCase.name, func(t *testing.T) {
			resolved, projectRoot, createOp := adoptRecipeOwnedOutput(t, fmt.Sprintf(regenerateRecipe, KindScaffolding))
			rule := declaredEnforcementRule(t, resolved)

			tokenLine := testCase.token(rule)
			diverged := divergedWithTokenLine(tokenLine)
			writeUnder(t, projectRoot, createOp.Target, diverged)

			result, err := Apply(resolved, ApplyOptions{Mode: ModeDirect, ProjectRoot: projectRoot})
			if err != nil {
				t.Fatalf("re-apply over a diverged file: unexpected error: %v", err)
			}

			got := snapshotTree(t, projectRoot)[createOp.Target]
			preserved, reported := preservedFor(result, createOp.Target)

			if !testCase.preserved {
				if got != regeneratedPayload {
					t.Errorf("diverged file = %q, want the regenerated payload %q — this token does not cover the divergence", got, regeneratedPayload)
				}
				if reported {
					t.Errorf("result reports %q as preserved (%+v); adjudication must reject this token", createOp.Target, preserved)
				}
				return
			}

			if got != diverged {
				t.Errorf("covered divergence = %q, want the consumer's bytes preserved verbatim %q", got, diverged)
			}
			if !reported {
				t.Fatalf("result.Preserved = %+v, want an entry for the covered divergence %q", result.Preserved, createOp.Target)
			}
			if preserved.Rule != rule {
				t.Errorf("preserved.Rule = %q, want the recipe's declared enforcement rule %q", preserved.Rule, rule)
			}
			if !strings.Contains(preserved.CoveringWaiver, "@waiver:"+rule+":") {
				t.Errorf("preserved.CoveringWaiver = %q, want the token that was READ from the consumer's file (%q)", preserved.CoveringWaiver, tokenLine)
			}
			for _, written := range result.Written {
				if written == createOp.Target {
					t.Errorf("result.Written reports %q; a preserved divergence is not a write", written)
				}
			}
		})
	}
}

// TestApply_DivergedNoWaiver_Regenerates proves an UNCOVERED divergence is
// overwritten (CLM-061). The diverged file is shaped exactly like the covered
// case — same lines, same edit — minus the token, so the only thing deciding the
// outcome is the adjudication.
func TestApply_DivergedNoWaiver_Regenerates(t *testing.T) {
	resolved, projectRoot, createOp := adoptRecipeOwnedOutput(t, fmt.Sprintf(regenerateRecipe, KindScaffolding))

	writeUnder(t, projectRoot, createOp.Target, divergedWithTokenLine("# no waiver token anywhere on this line"))

	result, err := Apply(resolved, ApplyOptions{Mode: ModeDirect, ProjectRoot: projectRoot})
	if err != nil {
		t.Fatalf("re-apply over an uncovered divergence: unexpected error: %v", err)
	}

	if got := snapshotTree(t, projectRoot)[createOp.Target]; got != regeneratedPayload {
		t.Errorf("uncovered divergence = %q, want the regenerated payload %q", got, regeneratedPayload)
	}
	if preserved, reported := preservedFor(result, createOp.Target); reported {
		t.Errorf("result reports %q as preserved (%+v); an uncovered divergence is regenerated", createOp.Target, preserved)
	}

	var regenerated bool
	for _, written := range result.Written {
		if written == createOp.Target {
			regenerated = true
		}
	}
	if !regenerated {
		t.Errorf("result.Written = %v, want the regenerated target %q", result.Written, createOp.Target)
	}
}

// TestApply_NeverAuthorsWaiverToken proves the applier calls no waiver-AUTHORING
// API (CLM-062). A waiver's reason and expiry are human judgments the consumer
// supplies by adding the token FIRST, so an applier that "helpfully" wrote one on
// a divergence would be manufacturing the accountability the token represents.
//
// The whole project tree is walked in both directions: zero tokens exist after an
// uncovered divergence, and the single pre-existing token is still exactly one
// after a covered one.
func TestApply_NeverAuthorsWaiverToken(t *testing.T) {
	t.Run("uncovered_divergence_authors_nothing", func(t *testing.T) {
		resolved, projectRoot, createOp := adoptRecipeOwnedOutput(t, fmt.Sprintf(regenerateRecipe, KindScaffolding))

		writeUnder(t, projectRoot, createOp.Target, divergedWithTokenLine("# a divergence with no waiver at all"))

		if _, err := Apply(resolved, ApplyOptions{Mode: ModeDirect, ProjectRoot: projectRoot}); err != nil {
			t.Fatalf("re-apply: unexpected error: %v", err)
		}

		tree := snapshotTree(t, projectRoot)
		if tokens := countWaiverTokens(tree); tokens != 0 {
			t.Errorf("project tree holds %d @waiver tokens across %v, want 0 — the applier never authors one", tokens, pathSet(tree))
		}
	})

	t.Run("covered_divergence_leaves_the_consumers_token_alone", func(t *testing.T) {
		resolved, projectRoot, createOp := adoptRecipeOwnedOutput(t, fmt.Sprintf(regenerateRecipe, KindScaffolding))
		rule := declaredEnforcementRule(t, resolved)

		writeUnder(t, projectRoot, createOp.Target, divergedWithTokenLine("# @waiver:"+rule+":deferred:2099-01-01 the consumer's own token"))

		if _, err := Apply(resolved, ApplyOptions{Mode: ModeDirect, ProjectRoot: projectRoot}); err != nil {
			t.Fatalf("re-apply: unexpected error: %v", err)
		}

		tree := snapshotTree(t, projectRoot)
		if tokens := countWaiverTokens(tree); tokens != 1 {
			t.Errorf("project tree holds %d @waiver tokens across %v, want exactly the 1 the consumer wrote", tokens, pathSet(tree))
		}
	})
}
