package main

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"gopkg.in/yaml.v3"
)

func testRepoRoot(t *testing.T) string {
	t.Helper()
	root, err := findRepoRoot(filepath.Join("..", ".."))
	if err != nil {
		t.Fatal(err)
	}
	return root
}

func loadOverlay(t *testing.T, root string) Overlay {
	t.Helper()
	raw, err := os.ReadFile(filepath.Join(root, overlayRelativePath))
	if err != nil {
		t.Fatal(err)
	}
	var overlay Overlay
	if err := yaml.Unmarshal(raw, &overlay); err != nil {
		t.Fatal(err)
	}
	return overlay
}

func entityByID(overlay Overlay, id string) Entity {
	for _, ent := range overlay.Entities {
		if ent.ID == id {
			return ent
		}
	}
	return Entity{}
}

func TestEntityRef_GeneratedPagesMatchSchemaAndOverlay(t *testing.T) {
	root := testRepoRoot(t)
	overlay := loadOverlay(t, root)
	for _, ent := range overlay.Entities {
		if ent.ID == "plan" {
			continue
		}
		got, err := render(root, ent)
		if err != nil {
			t.Fatalf("%s render: %v", ent.ID, err)
		}
		want, err := os.ReadFile(filepath.Join(root, ent.Output))
		if err != nil {
			t.Fatalf("%s read committed: %v", ent.Output, err)
		}
		if got != string(want) {
			t.Fatalf("%s rendered bytes differ from committed %s", ent.ID, ent.Output)
		}
	}
}

func TestEntityRef_CheckFailsOnDrift(t *testing.T) {
	root := testRepoRoot(t)
	if err := Run(root, true, ioDiscard{t: t}); err != nil {
		t.Fatalf("clean tree -check: %v", err)
	}
	temp := t.TempDir()
	copyTree(t, root, temp, []string{
		overlayRelativePath,
		"artifacts",
		"docs/issue.md",
		"docs/spec.md",
		"docs/bundle.md",
		"docs/directive.md",
		"docs/adr.md",
		"docs/capability.md",
		"docs/pack.md",
	})
	issuePath := filepath.Join(temp, "docs/issue.md")
	data, err := os.ReadFile(issuePath)
	if err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(issuePath, append(data, []byte("\n<!-- drift -->\n")...), 0o644); err != nil {
		t.Fatal(err)
	}
	if err := Run(temp, true, ioDiscard{t: t}); err == nil {
		t.Fatal("expected drift error on mutated page")
	} else if !strings.Contains(err.Error(), "drifted") {
		t.Fatalf("drift error = %v", err)
	}
}

type ioDiscard struct{ t *testing.T }

func (ioDiscard) Write(p []byte) (int, error) { return len(p), nil }

func copyTree(t *testing.T, src, dst string, relPaths []string) {
	t.Helper()
	for _, rel := range relPaths {
		srcPath := filepath.Join(src, rel)
		dstPath := filepath.Join(dst, rel)
		info, err := os.Stat(srcPath)
		if err != nil {
			t.Fatal(err)
		}
		if info.IsDir() {
			if err := copyDir(t, srcPath, dstPath); err != nil {
				t.Fatal(err)
			}
			continue
		}
		if err := os.MkdirAll(filepath.Dir(dstPath), 0o755); err != nil {
			t.Fatal(err)
		}
		raw, err := os.ReadFile(srcPath)
		if err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(dstPath, raw, 0o644); err != nil {
			t.Fatal(err)
		}
	}
}

func copyDir(t *testing.T, src, dst string) error {
	t.Helper()
	return filepath.WalkDir(src, func(path string, entry os.DirEntry, err error) error {
		if err != nil {
			return err
		}
		rel, err := filepath.Rel(src, path)
		if err != nil {
			return err
		}
		target := filepath.Join(dst, rel)
		if entry.IsDir() {
			return os.MkdirAll(target, 0o755)
		}
		raw, err := os.ReadFile(path)
		if err != nil {
			return err
		}
		return os.WriteFile(target, raw, 0o644)
	})
}

func TestEntityRef_SkipsLockedPlanPage(t *testing.T) {
	root := testRepoRoot(t)
	overlay := loadOverlay(t, root)
	for _, ent := range overlay.Entities {
		if ent.ID != "plan" {
			continue
		}
		if _, err := render(root, ent); err != nil {
			t.Fatalf("plan render: %v (Run must still skip writing plan.md)", err)
		}
	}
	planPath := filepath.Join(root, "docs/plan.md")
	data, err := os.ReadFile(planPath)
	if err != nil {
		t.Fatal(err)
	}
	body := string(data)
	if strings.Contains(body, "generated by go run ./scripts/entityref") {
		t.Fatal("plan.md must not carry generator provenance")
	}
	for _, sentence := range []string{
		"A plan is the bound on implementation. Nobody writes product code until one is approved.",
		"Reactive work uses issue → plan. Feature work uses bundle → spec → plan. Both tracks meet here.",
		"The source artifact defines the work. The plan is the handoff. An implementer executes the approved plan and runs required gates as it works.",
	} {
		if !strings.Contains(body, sentence) {
			t.Fatalf("plan.md missing locked note: %q", sentence)
		}
	}
	if !strings.Contains(body, "## Work path") {
		t.Fatal("plan.md missing Work path section")
	}
	for _, link := range []string{`href="/issue/"`, `href="/spec/"`, `href="/bundle/"`, `href="/model/#operating-model"`} {
		if !strings.Contains(body, link) {
			t.Fatalf("plan.md missing also-link %s", link)
		}
	}
	if strings.Contains(body, "/reference/#artifact-schema-catalog") {
		t.Fatal("plan.md must not link artifact schema catalog per approved IA")
	}
}

func TestEntityRef_LockedLedesAndWorkPathRows(t *testing.T) {
	ledes := map[string]string{
		"plan":       "Ordered work an agent can execute. It comes from an issue or a spec.",
		"issue":      "Bounded work that does not need a bundle and spec. It becomes a plan.",
		"spec":       "Requirements and claims for a slice of feature work. It comes from a bundle. It becomes a plan.",
		"bundle":     "A larger body of work. It decomposes into specs. Each spec becomes a plan.",
		"directive":  "A backlog item. Position in BACKLOG.yml is priority. It cites the work that authorized it.",
		"adr":        "A recorded decision. It is evidence for later work. It is not a path into implementation.",
		"capability": "What a user can do, proved end to end. Specs implement the pieces. The capability verifies the journey.",
		"pack":       "A versioned set of standards, engines, and proof. Packs are not intent artifacts.",
	}
	root := testRepoRoot(t)
	overlay := loadOverlay(t, root)
	for id, lede := range ledes {
		if id == "plan" {
			planBody, err := os.ReadFile(filepath.Join(root, "docs/plan.md"))
			if err != nil {
				t.Fatal(err)
			}
			if !strings.Contains(string(planBody), lede) {
				t.Fatalf("plan page missing lede %q", lede)
			}
			continue
		}
		ent := entityByID(overlay, id)
		if ent.HeroLede != lede {
			t.Fatalf("%s overlay lede = %q, want %q", id, ent.HeroLede, lede)
		}
		path := filepath.Join(root, ent.Output)
		body, err := os.ReadFile(path)
		if err != nil {
			t.Fatalf("%s: %v", id, err)
		}
		text := string(body)
		if !strings.Contains(text, lede) {
			t.Fatalf("%s page missing lede %q", id, lede)
		}
		if strings.Contains(text, "## Sources") {
			t.Fatalf("%s page contains forbidden Sources heading", id)
		}
	}
	planBody, _ := os.ReadFile(filepath.Join(root, "docs/plan.md"))
	plan := string(planBody)
	if !strings.Contains(plan, "<th>Work</th>") || !strings.Contains(plan, "<th>Path</th>") {
		t.Fatal("plan Work path table missing Work/Path headers")
	}
	if !strings.Contains(plan, "Feature / substantial") || !strings.Contains(plan, "Small / reactive") {
		t.Fatal("plan must carry both work-path rows")
	}
	issueBody, _ := os.ReadFile(filepath.Join(root, "docs/issue.md"))
	if !strings.Contains(string(issueBody), "Small / reactive") || strings.Contains(string(issueBody), "Feature / substantial") {
		t.Fatal("issue must carry only small/reactive work-path row")
	}
	for _, id := range []string{"spec", "bundle"} {
		ent := entityByID(overlay, id)
		body, _ := os.ReadFile(filepath.Join(root, ent.Output))
		text := string(body)
		if !strings.Contains(text, "Feature / substantial") || strings.Contains(text, "Small / reactive") {
			t.Fatalf("%s must carry only feature/substantial work-path row", id)
		}
	}
	for _, id := range []string{"pack", "directive", "adr", "capability"} {
		ent := entityByID(overlay, id)
		body, _ := os.ReadFile(filepath.Join(root, ent.Output))
		if strings.Contains(string(body), "## Work path") {
			t.Fatalf("%s must not have Work path section", id)
		}
	}
}

func TestEntityRef_PackPageCarriesConstraintsAndNoWorkPath(t *testing.T) {
	root := testRepoRoot(t)
	body, err := os.ReadFile(filepath.Join(root, "docs/pack.md"))
	if err != nil {
		t.Fatal(err)
	}
	text := string(body)
	if !strings.Contains(text, "<dt>Kind</dt><dd>Pack</dd>") {
		t.Fatal("pack page must render KIND Pack")
	}
	if strings.Contains(text, "## Work path") {
		t.Fatal("pack page must not have Work path section")
	}
	for _, c := range []string{
		"Packs are not intent artifacts.",
		"A pack is not a path into implementation.",
		"Implementation still requires an approved plan.",
		"Packs live outside core. The lock file is the durability boundary.",
	} {
		if !strings.Contains(text, c) {
			t.Fatalf("pack page missing constraint %q", c)
		}
	}
	if strings.Contains(strings.ToLower(text), "enforcement") {
		t.Fatal("pack page must not dump enforcement jargon")
	}
}

func TestEntityRef_AlsoLinksResolveToLandedRoutes(t *testing.T) {
	root := testRepoRoot(t)
	overlay := loadOverlay(t, root)
	routes := map[string]bool{}
	for _, route := range append(canonicalRoutesForTest(), extraLinkableRoutesForTest()...) {
		routes[route] = true
	}
	for _, ent := range overlay.Entities {
		for _, link := range ent.Also {
			if !strings.HasPrefix(link.Href, "/") {
				t.Fatalf("%s also-link %q is not root-relative", ent.ID, link.Href)
			}
			// Approved IA supersession: the artifact-schema-catalog target resolves on
			// origin/main, but Reference teases stay removed from entity pages.
			if strings.Contains(link.Href, "/reference/#artifact-schema-catalog") {
				t.Fatalf("%s must not link artifact schema catalog per approved IA", ent.ID)
			}
			path := link.Href
			if idx := strings.Index(path, "#"); idx >= 0 {
				path = path[:idx]
			}
			if path == "" {
				continue
			}
			if !routes[path] {
				t.Fatalf("%s also-link %q names missing route %q", ent.ID, link.Href, path)
			}
		}
	}
	pack := entityByID(overlay, "pack")
	got := map[string]bool{}
	for _, link := range pack.Also {
		got[link.Href] = true
	}
	for _, href := range []string{"/pack/examples/", "/pack/guide/"} {
		if !got[href] {
			t.Fatalf("pack also-links must include %s", href)
		}
	}
}

func canonicalRoutesForTest() []string {
	return []string{"/", "/evaluate/", "/model/", "/adopt/", "/use-cases/", "/pack/examples/", "/pack/guide/", "/reference/", "/status/", "/contributing/"}
}

func extraLinkableRoutesForTest() []string {
	return []string{"/pack/", "/plan/", "/issue/", "/spec/", "/bundle/", "/directive/", "/adr/", "/capability/"}
}

func TestEntityRef_SchemaDerivationHelpersMatrix(t *testing.T) {
	if got := humanizePattern(`^ISSUE-[0-9]{3}(-[a-z0-9-]+)?\.issue\.md$`); !strings.Contains(got, "NNN") {
		t.Fatalf("humanizePattern issue filename = %q", got)
	}
	if got := humanizePattern(`^[0-9]{4}-[0-9]{2}-[0-9]{2}$`); got != "YYYY-MM-DD" {
		t.Fatalf("humanizePattern date = %q", got)
	}
	enumProp := map[string]any{"enum": []any{"draft", "ready"}}
	if got := fieldForm(enumProp); got != "`draft` · `ready`" {
		t.Fatalf("fieldForm enum = %q", got)
	}
	if got := fieldForm(map[string]any{"const": "issue/v1"}); got != "issue/v1" {
		t.Fatalf("fieldForm const = %q", got)
	}
	if got := fieldForm(map[string]any{"pattern": `^[a-z][a-z0-9]*(-[a-z0-9]+)*$`}); got != "slug" {
		t.Fatalf("fieldForm pattern = %q", got)
	}
	if got := fieldForm(map[string]any{"type": "integer"}); got != "integer" {
		t.Fatalf("fieldForm type = %q", got)
	}
	if got := fieldForm(nil); got != "string" {
		t.Fatalf("fieldForm nil = %q", got)
	}

	root := testRepoRoot(t)
	schema := map[string]any{
		"extends": "artifacts/base/schema.json",
		"metadata": map[string]any{
			"properties": map[string]any{
				"status": map[string]any{"type": "string"},
			},
		},
	}
	merged := mergeBase(root, schema)
	if merged == nil {
		t.Fatal("mergeBase returned nil")
	}
	if mergeBase(root, map[string]any{"extends": ""}) == nil {
		t.Fatal("mergeBase no-extends returned nil")
	}
	if mergeBase(t.TempDir(), map[string]any{"extends": "artifacts/base/schema.json"}) == nil {
		t.Fatal("mergeBase missing base file returned nil")
	}
	if mergeBase(root, map[string]any{"extends": "artifacts/base/schema.json", "metadata": "bad"}) == nil {
		t.Fatal("mergeBase bad metadata returned nil")
	}

	overlayOnly := Entity{
		ID: "pack", StatusMeanings: map[string]string{"installed": "ready", "draft": "wip"},
	}
	values := statusValues(map[string]any{}, "")
	if len(values) != 0 {
		t.Fatalf("statusValues empty path = %#v", values)
	}
	rendered, err := render(root, overlayOnly)
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(rendered, "## Status") {
		t.Fatal("overlay status meanings fallback missing Status section")
	}

	noSections := sectionTable(map[string]any{})
	if noSections != "" {
		t.Fatal("sectionTable without required_sections must be empty")
	}
	withSections := sectionTable(map[string]any{
		"required_sections": []any{"Claims"},
		"optional_sections": []any{"Notes"},
	})
	if !strings.Contains(withSections, "Claims") || !strings.Contains(withSections, ">yes<") || !strings.Contains(withSections, ">no<") {
		t.Fatalf("sectionTable = %q", withSections)
	}

	illegal := illegalBlock([]string{"replaced", "obsoleted"}, Entity{ExtraIllegal: []string{"custom rule"}})
	for _, want := range []string{"replaced", "obsoleted", "custom rule"} {
		if !strings.Contains(illegal, want) {
			t.Fatalf("illegalBlock missing %q in %q", want, illegal)
		}
	}

	if got := mdCode("plain `code` tail"); got != `plain <code>code</code> tail` {
		t.Fatalf("mdCode balanced = %q", got)
	}
	if got := mdCode("unbalanced `code"); !strings.Contains(got, "unbalanced") {
		t.Fatalf("mdCode unbalanced = %q", got)
	}
	if got := escape(`<a href="x">`); got != `&lt;a href=&quot;x&quot;&gt;` {
		t.Fatalf("escape = %q", got)
	}
	if got := schemaVersion(map[string]any{
		"artifact_type": "bundle",
		"version":       "2.0",
	}, Entity{ID: "bundle"}); got != "bundle/v2" {
		t.Fatalf("schemaVersion v2 = %q", got)
	}
}

func TestEntityRef_RootResolutionAndErrorPaths(t *testing.T) {
	root := testRepoRoot(t)
	if got, err := findRepoRoot(root); err != nil || got != root {
		t.Fatalf("findRepoRoot from repo = %q, %v", got, err)
	}
	missing := filepath.Join(t.TempDir(), "nowhere")
	if _, err := findRepoRoot(missing); err == nil {
		t.Fatal("expected error when overlay missing")
	} else if !strings.Contains(err.Error(), overlayRelativePath) {
		t.Fatalf("error = %v", err)
	}
	temp := t.TempDir()
	if err := os.MkdirAll(filepath.Join(temp, "docs", "_data"), 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(temp, overlayRelativePath), []byte("entities: []\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	if _, err := findRepoRoot(temp); err != nil {
		t.Fatalf("findRepoRoot with overlay only: %v", err)
	}
	badOverlay := filepath.Join(t.TempDir(), overlayRelativePath)
	if err := os.MkdirAll(filepath.Dir(badOverlay), 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(badOverlay, []byte(":\tbad\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	if err := Run(filepath.Dir(filepath.Dir(filepath.Dir(badOverlay))), false, ioDiscard{t: t}); err == nil {
		t.Fatal("expected parse overlay error")
	}
	invalidEntity := t.TempDir()
	copyTree(t, root, invalidEntity, []string{overlayRelativePath})
	overlay := loadOverlay(t, invalidEntity)
	for i := range overlay.Entities {
		if overlay.Entities[i].ID == "issue" {
			overlay.Entities[i].Schema = "missing/schema.json"
		}
	}
	raw, _ := yaml.Marshal(overlay)
	_ = os.WriteFile(filepath.Join(invalidEntity, overlayRelativePath), raw, 0o644)
	if err := Run(invalidEntity, false, ioDiscard{t: t}); err == nil {
		t.Fatal("expected render error for missing schema")
	}
}

func TestEntityRef_RenderLookupProp(t *testing.T) {
	schema := map[string]any{
		"metadata": map[string]any{
			"properties": map[string]any{
				"title": map[string]any{"type": "string"},
			},
		},
		"nested_blocks": map[string]any{
			"issue": map[string]any{
				"properties": map[string]any{
					"status": map[string]any{"enum": []any{"open"}},
				},
			},
		},
	}
	if lookupProp(schema, "issue.status") == nil {
		t.Fatal("lookupProp nested path returned nil")
	}
	table := fieldsTable(schema, []FieldSpec{{Key: "title"}})
	if !strings.Contains(table, "<code>title</code>") {
		t.Fatalf("fieldsTable = %q", table)
	}
}

func TestEntityRef_PlanOutputUnchanged(t *testing.T) {
	root := testRepoRoot(t)
	if err := Run(root, false, ioDiscard{t: t}); err != nil {
		t.Fatal(err)
	}
	planBefore, _ := os.ReadFile(filepath.Join(root, "docs/plan.md"))
	if strings.Contains(string(planBefore), "generated by go run ./scripts/entityref") {
		t.Fatal("Run must not touch plan.md")
	}
}